"""
utils/export.py — PDF and Markdown export helpers.

Generates downloadable report files from a Report instance.
PDF generation uses ReportLab with a professional layout:
  - Cover page with startup name, metadata, and readiness score
  - Section headings styled in brand blue
  - Body text with proper line spacing
  - Safe HTML escaping to prevent ReportLab XML parse errors
  - All Markdown symbols stripped before rendering to PDF

Markdown export preserves all original Markdown formatting for
use in editors, GitHub, and document converters.
"""

import logging
import os
import re
from datetime import datetime
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    HRFlowable,
    PageBreak,
    KeepTogether,
)
from reportlab.lib import colors

from config.settings import settings
from config.constants import APP_NAME, APP_VERSION, REPORT_SECTIONS
from utils.file_utils import ensure_dir

logger = logging.getLogger(__name__)

# Brand colour constants
_COLOR_DARK   = colors.HexColor("#1f2328")
_COLOR_BLUE   = colors.HexColor("#3b82d4")
_COLOR_MUTED  = colors.HexColor("#57606a")
_COLOR_BORDER = colors.HexColor("#e5e7eb")
_COLOR_BG     = colors.HexColor("#f7f8fa")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_markdown(report) -> str:
    """Serialise a Report to Markdown and save it to the exports directory.

    Args:
        report: A :class:`core.report_builder.Report` instance.

    Returns:
        The full Markdown string (also written to disk).
    """
    lines: list[str] = [
        f"# {report.startup_input.startup_name} — Startup Blueprint",
        f"> Generated by {APP_NAME} v{APP_VERSION}  ",
        f"> {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        f"**Industry:** {report.startup_input.industry}  ",
        f"**Country:** {report.startup_input.country}  ",
        f"**Stage:** {report.startup_input.startup_stage}  ",
        f"**Budget:** {report.startup_input.budget}",
    ]

    if report.readiness_score is not None and report.readiness_score > 0:
        lines.append(
            f"**Startup Readiness Score:** {report.readiness_score} / 100"
        )

    lines += ["", "---", ""]

    for section in REPORT_SECTIONS:
        content = report.get_section(section)
        lines.append(f"## {section}")
        lines.append("")
        lines.append(content if content else "_Not generated._")
        lines.append("")

    markdown = "\n".join(lines)

    ensure_dir(settings.exports_dir)
    filename = _safe_filename(report.startup_input.startup_name) + "_blueprint.md"
    filepath = os.path.join(settings.exports_dir, filename)
    with open(filepath, "w", encoding="utf-8") as fh:
        fh.write(markdown)

    logger.info("Markdown report saved: %s", filepath)
    return markdown


def export_pdf(report) -> bytes:
    """Generate a PDF report and return the raw bytes.

    The PDF is also saved to the exports directory as a side effect.

    Args:
        report: A :class:`core.report_builder.Report` instance.

    Returns:
        PDF file contents as raw bytes.
    """
    ensure_dir(settings.exports_dir)
    filename = _safe_filename(report.startup_input.startup_name) + "_blueprint.pdf"
    filepath = os.path.join(settings.exports_dir, filename)

    styles = _build_styles()
    story  = _build_story(report, styles)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=2.2 * cm,
        rightMargin=2.2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title=f"{report.startup_input.startup_name} — Startup Blueprint",
        author=APP_NAME,
    )
    doc.build(story)
    logger.info("PDF report saved: %s", filepath)

    with open(filepath, "rb") as fh:
        return fh.read()


# ---------------------------------------------------------------------------
# Style definitions
# ---------------------------------------------------------------------------

def _build_styles() -> dict:
    """Return a dict of named ReportLab ParagraphStyle objects.

    Returns:
        Dictionary mapping style name → ParagraphStyle.
    """
    base = getSampleStyleSheet()

    return {
        "cover_title": ParagraphStyle(
            "VPCoverTitle",
            parent=base["Title"],
            fontSize=26,
            leading=32,
            spaceAfter=8,
            textColor=_COLOR_DARK,
            alignment=TA_CENTER,
        ),
        "cover_sub": ParagraphStyle(
            "VPCoverSub",
            parent=base["Normal"],
            fontSize=11,
            leading=16,
            spaceAfter=4,
            textColor=_COLOR_MUTED,
            alignment=TA_CENTER,
        ),
        "cover_score": ParagraphStyle(
            "VPCoverScore",
            parent=base["Normal"],
            fontSize=14,
            leading=20,
            spaceAfter=4,
            textColor=_COLOR_BLUE,
            alignment=TA_CENTER,
        ),
        "section_heading": ParagraphStyle(
            "VPSectionHeading",
            parent=base["Heading2"],
            fontSize=13,
            leading=18,
            spaceBefore=16,
            spaceAfter=6,
            textColor=_COLOR_BLUE,
            alignment=TA_LEFT,
        ),
        "body": ParagraphStyle(
            "VPBody",
            parent=base["Normal"],
            fontSize=10,
            leading=15,
            spaceAfter=6,
            textColor=_COLOR_DARK,
        ),
        "muted": ParagraphStyle(
            "VPMuted",
            parent=base["Normal"],
            fontSize=9,
            leading=13,
            spaceAfter=4,
            textColor=_COLOR_MUTED,
        ),
    }


# ---------------------------------------------------------------------------
# Story assembly
# ---------------------------------------------------------------------------

def _build_story(report, styles: dict) -> list:
    """Assemble the full list of ReportLab flowables for the PDF.

    Args:
        report: Report instance.
        styles: Dict of named ParagraphStyle objects.

    Returns:
        List of ReportLab flowable objects.
    """
    story: list = []

    # ── Cover page ──────────────────────────────────────────────────────────
    story += _build_cover(report, styles)
    story.append(PageBreak())

    # ── Report sections ──────────────────────────────────────────────────────
    for section in REPORT_SECTIONS:
        content = report.get_section(section)
        story += _build_section(section, content, styles)

    return story


def _build_cover(report, styles: dict) -> list:
    """Build cover page flowables.

    Args:
        report: Report instance.
        styles: Style dict.

    Returns:
        List of flowables for the cover page.
    """
    si = report.startup_input
    generated_at = datetime.now().strftime("%d %B %Y, %H:%M")

    elements: list = [
        Spacer(1, 3 * cm),
        Paragraph(_escape(si.startup_name), styles["cover_title"]),
        Paragraph("Startup Blueprint", styles["cover_sub"]),
        Spacer(1, 0.5 * cm),
        HRFlowable(width="60%", thickness=1, color=_COLOR_BORDER, hAlign="CENTER"),
        Spacer(1, 0.5 * cm),
        Paragraph(f"Industry: {_escape(si.industry)}", styles["cover_sub"]),
        Paragraph(f"Country: {_escape(si.country)}", styles["cover_sub"]),
        Paragraph(f"Stage: {_escape(si.startup_stage)}", styles["cover_sub"]),
        Paragraph(f"Budget: {_escape(si.budget)}", styles["cover_sub"]),
        Spacer(1, 0.8 * cm),
    ]

    if report.readiness_score is not None:
        elements += [
            Paragraph(
                f"Startup Readiness Score: {report.readiness_score} / 100",
                styles["cover_score"],
            ),
            Spacer(1, 0.4 * cm),
        ]

    elements += [
        HRFlowable(width="60%", thickness=1, color=_COLOR_BORDER, hAlign="CENTER"),
        Spacer(1, 0.4 * cm),
        Paragraph(
            f"Generated by {APP_NAME} v{APP_VERSION} &nbsp;|&nbsp; {generated_at}",
            styles["muted"],
        ),
    ]
    return elements


def _build_section(name: str, content: str, styles: dict) -> list:
    """Build flowables for a single report section.

    Args:
        name:    Section name string.
        content: Section body text (may contain Markdown).
        styles:  Style dict.

    Returns:
        List of flowables wrapped in KeepTogether where practical.
    """
    heading = Paragraph(_escape(name), styles["section_heading"])
    divider = HRFlowable(
        width="100%", thickness=0.5, color=_COLOR_BORDER, spaceAfter=4
    )

    if not content:
        body = Paragraph("<i>Not generated.</i>", styles["muted"])
        return [KeepTogether([heading, divider, body, Spacer(1, 0.3 * cm)])]

    # Convert content to ReportLab-safe paragraphs
    paragraphs = _content_to_paragraphs(content, styles["body"])
    return [heading, divider] + paragraphs + [Spacer(1, 0.4 * cm)]


def _content_to_paragraphs(text: str, style: ParagraphStyle) -> list:
    """Convert a Markdown/plain-text block into ReportLab Paragraph objects.

    Handles:
        - Blank line separation into distinct paragraphs
        - Markdown table rows (rendered as plain pipe-separated text)
        - Bold (**text**) → <b>text</b>
        - Bullets (- item) → • item

    Args:
        text:  Raw section content string.
        style: ParagraphStyle to apply.

    Returns:
        List of Paragraph flowables.
    """
    paragraphs: list = []

    for block in re.split(r"\n{2,}", text.strip()):
        block = block.strip()
        if not block:
            continue

        lines = block.split("\n")
        rendered_lines: list[str] = []

        for line in lines:
            line = line.strip()
            if not line:
                continue
            # Markdown table separator rows
            if re.match(r"^\|[-:| ]+\|$", line):
                continue
            # Bullet points
            if line.startswith("- ") or line.startswith("* "):
                line = "• " + line[2:]
            # Bold: **text** → <b>text</b>
            line = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", line)
            # Italic: *text* → <i>text</i>
            line = re.sub(r"\*(.+?)\*", r"<i>\1</i>", line)
            # Escape remaining XML special chars (except our tags)
            line = _escape_partial(line)
            rendered_lines.append(line)

        if rendered_lines:
            combined = "<br/>".join(rendered_lines)
            try:
                paragraphs.append(Paragraph(combined, style))
            except Exception:
                # If ReportLab still chokes, strip all tags and retry
                safe = re.sub(r"<[^>]+>", "", combined)
                paragraphs.append(Paragraph(_escape(safe), style))

    return paragraphs


# ---------------------------------------------------------------------------
# Escaping helpers
# ---------------------------------------------------------------------------

def _escape(text: str) -> str:
    """Escape a plain string for safe ReportLab XML rendering.

    Args:
        text: Raw string.

    Returns:
        XML-escaped string.
    """
    return (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
    )


def _escape_partial(text: str) -> str:
    """Escape XML special chars in a string that may already contain
    safe ReportLab tags (<b>, <i>, <br/>).

    Preserves <b>, </b>, <i>, </i>, <br/> tags.
    Escapes bare & and any other < > characters.

    Args:
        text: String possibly containing approved tags.

    Returns:
        Safely escaped string.
    """
    # Protect approved tags
    protected = re.sub(
        r"<(/?(?:b|i|br/?))\s*>",
        lambda m: f"\x00TAG{m.group(1)}\x00",
        text,
    )
    # Escape XML specials
    escaped = (
        protected.replace("&", "&amp;")
                 .replace("<", "&lt;")
                 .replace(">", "&gt;")
    )
    # Restore approved tags
    result = re.sub(r"\x00TAG(/?(?:b|i|br/?))\x00", r"<\1>", escaped)
    return result


def _safe_filename(name: str) -> str:
    """Convert a startup name into a filesystem-safe filename prefix.

    Args:
        name: Startup name from user input.

    Returns:
        Sanitised lowercase string.
    """
    return "".join(
        c if c.isalnum() or c in "._-" else "_" for c in name
    ).lower()
